# Generated by Django 5.1.7 on 2025-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='drive_link',
            field=models.URLField(),
        ),
    ]
